parallel-ssh -h temp date &
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
parallel-ssh -h temp date & 
